server:
  port: 8085

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resource-server:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        #Speedrun-service
        - id: speedrun-all
          uri: http://${SPEEDRUN_SERVICE_BASEURL}
          predicates:
            - Path=/speedruns
            - Method=GET
          filters:
            - SetPath=/api/speedruns/all
        - id: speedrun-start
          uri: http://${SPEEDRUN_SERVICE_BASEURL}
          predicates:
            - Path=/speedruns/start
            - Method=POST
          filters:
            - SetPath=/api/speedruns/start
        - id: speedrun-end
          uri: http://${SPEEDRUN_SERVICE_BASEURL}
          predicates:
            - Path=/speedruns/end
            - Method=POST
          filters:
            - SetPath=/api/speedruns/end
        - id: speedrun-profile
          uri: http://${SPEEDRUN_SERVICE_BASEURL}
          predicates:
            - Path=/speedruns/profile
            - Method=GET
          filters:
            - SetPath=/api/speedruns/profiles
        #Game-service
        - id: game-all
          uri: http://${GAME_SERVICE_BASEURL}
          predicates:
            - Path=/games
            - Method=GET
          filters:
            - SetPath=/api/games/all
        - id: game-top5
          uri: http://${GAME_SERVICE_BASEURL}
          predicates:
            - Path=/games/top5
            - Method=GET
          filters:
            - SetPath=/api/games/top5
        #Profile-service
        - id: profile-service
          uri: http://${PROFILE_SERVICE_BASEURL}
          predicates:
            - Path=/profiles
            - Method=GET
          filters:
            - SetPath=/api/profiles/all