#mysql-prometheus deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-prometheus
  labels:
    service: mysql-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mysql-prometheus
  template:
    metadata:
      labels:
        service: mysql-prometheus
    spec:
      containers:
      - name: mysql-prometheus
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: abc123
        volumeMounts:
        - name: mysql-prometheus-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-prometheus-data
        persistentVolumeClaim:
          claimName: mysql-prometheus-data