# gateway-service service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    service: api-gateway-service
spec:
  type: NodePort
  ports:
  - port: 8085
    targetPort: 8085
  selector:
    service: api-gateway-service