# game-service service
apiVersion: v1
kind: Service
metadata:
  name: game-service
  labels:
    service: game-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    service: game-service