# mysql-prometheus service
apiVersion: v1
kind: Service
metadata:
  name: mysql-prometheus
  labels:
    service: mysql-prometheus
spec:
  ports:
  - port: 3309
    targetPort: 3306
  selector:
    service: mysql-prometheus