#Prometheus service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: speedrun-application
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  selector: 
    app: prometheus-server
  type: NodePort  
  ports:
    - port: 8086
      targetPort: 9090